server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    add_header Cross-Origin-Opener-Policy "unsafe-none" always;
    add_header Cross-Origin-Embedder-Policy "unsafe-none" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
