{
 "title": "AlloyDB Omni Dashboard",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up,dbnamespace)"
    }
   },
   {
    "name": "dbcluster",
    "label": "dbcluster",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up{dbnamespace=\"$namespace\"},dbcluster)"
    }
   },
   {
    "name": "dbinstance_type",
    "label": "dbinstance_type",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up{dbcluster=\"$dbcluster\"},dbinstance_type)"
    }
   },
   {
    "name": "dbinstance",
    "label": "dbinstance",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up{dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\"},dbinstance)"
    }
   },
   {
    "name": "dbnode_type",
    "label": "dbnode_type",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up{dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\"},dbnode_type)"
    }
   },
   {
    "name": "dbnode",
    "label": "dbnode",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up{dbcluster=\"$dbcluster\", dbnode_type=\"$dbnode_type\"},dbnode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "AlloyDB Omni", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Monitoring\n\n" } },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Service up",
   "type": "timeseries",
   "description": "Whether the Postgres main process is running, 1 if running, 0 if down.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_up{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Percentage utilization of the reserved CPU that's currently in use.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1000 * (rate(alloydb_omni_node_cpu_usage_second_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m]) / alloydb_omni_node_cpu_mcpu{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory components",
   "type": "timeseries",
   "description": "Estimate of the amount of memory allocated to the AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "repeat": "dbnode",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "alloydb_omni_memory_available_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"} / alloydb_omni_memory_limit_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "available_{{dbnode}}"
    },
    {
     "expr": "alloydb_omni_memory_limit_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"} / alloydb_omni_memory_limit_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "limit_{{dbnode}}"
    },
    {
     "expr": "alloydb_omni_memory_used_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"} / alloydb_omni_memory_limit_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "used_{{dbnode}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "description": "Size of the database in each AlloyDB Omni instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_size_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage limit per disk",
   "type": "timeseries",
   "description": "Storage capacity allocated to each disk attached to the AlloyDB Omni instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alloydb_omni_node_storage_limit_per_disk_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage utilization",
   "type": "timeseries",
   "description": "Percentage of allocated storage currently used on each disk attached to the AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "alloydb_omni_node_storage_usage_per_disk_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"} / alloydb_omni_node_storage_limit_per_disk_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait time",
   "type": "timeseries",
   "description": "Accumulated elapsed wait time per wait event for each AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "expr": "1000 * rate(alloydb_omni_instance_postgresql_wait_time_second_total{wait_event_name!=\"ClientRead\", externally_visible=\"true\", dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait count",
   "type": "timeseries",
   "description": "Number of times the processes waited per wait event for each AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_instance_postgresql_wait_count_total{externally_visible=\"true\", wait_event_name!=\"ClientRead\", dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "description": "Number of active and idle connections to the AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_backends{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic received",
   "type": "timeseries",
   "description": "Amount of network received bytes count per second on the AlloyDB Omni pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_node_network_received_bytes_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic sent",
   "type": "timeseries",
   "description": "Amount of network sent bytes count per second on the AlloyDB Omni pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_node_network_sent_bytes_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction ID utilization",
   "type": "timeseries",
   "description": "Percentage of transaction ID space consumed by the AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_vacuum_transaction_id_utilization_percentage{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oldest transaction age",
   "type": "timeseries",
   "description": "Current age of the oldest uncommitted transaction for each AlloyDB Omni instance that's blocking the vacuum operation. Measured in the number of transactions that started after the oldest transaction.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_vacuum_oldest_transaction_age{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction count",
   "type": "timeseries",
   "description": "Number of committed transactions per second to the AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_instance_postgresql_committed_transactions_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read pool replication lag",
   "type": "timeseries",
   "description": "Time elapsed (milliseconds) in the replication from primary to read replica.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "alloydb_omni_instance_postgresql_replication_replay_lag_ms{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"Primary\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Advanced Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Rows processed by operation",
   "type": "timeseries",
   "description": "Number of rows processed by operations (insert, update, delete) in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_deleted_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_inserted_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_updated_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows in database by state",
   "type": "timeseries",
   "description": "Number of live and dead rows in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_tuples{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temp data size used",
   "type": "timeseries",
   "description": "Amount of data written to temporary files by queries in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_temp_bytes_written_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temp files used",
   "type": "timeseries",
   "description": "Number of temporary files used for writing data while performing internal algorithms in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_temp_files_written_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlock count",
   "type": "timeseries",
   "description": "Number of deadlocks in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_deadlock_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block read count",
   "type": "timeseries",
   "description": "Number of blocks read by Postgres from disk and buffer cache in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_blks_hit_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(alloydb_omni_database_postgresql_blks_read_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statements executed count",
   "type": "timeseries",
   "description": "Number of statements executed in each AlloyDB Omni instance per database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_statements_executed_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New connections count",
   "type": "timeseries",
   "description": "Number of new connections added to each AlloyDB Omni instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_instance_postgresql_new_connections_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=\"$dbnode\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}