apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloydb-omni-metrics
  namespace: {{ .Values.kpsNamespace | quote }}
spec:
  # The namespace where the *Service* you want to scrape lives
  namespaceSelector:
    matchNames:
      - {{ .Values.alloydb.namespace | quote }}

  # How to find the Service (by its labels)
  selector:
    matchLabels:
      app: {{ .Values.alloydb.appLabel | quote }}

  endpoints:
    - # Port where metrics are exposed
      # If your Service's port has a *name*, it's better to use that name here.
      # If not, using the number is okay.
      port: {{ .Values.alloydb.metricsPort | quote }}
      path: /metrics
      interval: 30s

