apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
spec:
  selector:
    matchLabels:
      app: {{.Values.alloydb.appLabel | quote}}
  endpoints:
  - port: {{.Values.alloydb.metricsPort}}
  interval: {{.Values.alloydb.interval | quote}}
metadata:
  name: {{ .Release.Name }}-alloydb-omni-metrics
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.alloydb.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.alloydb.appLabel | quote }}
  endpoints:
  - port: {{ .Values.alloydb.metricsPort }}
    interval: {{ .Values.alloydb.interval | quote }}
