// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v2/common/proto/anomaly_finding_entry.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the structural finding output by the anomaly detection service.
type AnomalyFinding struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs             int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	DbUser                  string                 `protobuf:"bytes,2,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbName                  string                 `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	QueryStatement          string                 `protobuf:"bytes,4,opt,name=query_statement,json=queryStatement,proto3" json:"query_statement,omitempty"`
	NormalizedQueryTemplate string                 `protobuf:"bytes,5,opt,name=normalized_query_template,json=normalizedQueryTemplate,proto3" json:"normalized_query_template,omitempty"`
	// Predict anomaly status for human review and model performance measurement.
	IsAnomalousPredict bool `protobuf:"varint,6,opt,name=is_anomalous_predict,json=isAnomalousPredict,proto3" json:"is_anomalous_predict,omitempty"`
	// Measure ML model's level of certainty in its prediction.
	ConfidenceScore float64 `protobuf:"fixed64,7,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnomalyFinding) Reset() {
	*x = AnomalyFinding{}
	mi := &file_v2_common_proto_anomaly_finding_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyFinding) ProtoMessage() {}

func (x *AnomalyFinding) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_anomaly_finding_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyFinding.ProtoReflect.Descriptor instead.
func (*AnomalyFinding) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_anomaly_finding_entry_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyFinding) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AnomalyFinding) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *AnomalyFinding) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *AnomalyFinding) GetQueryStatement() string {
	if x != nil {
		return x.QueryStatement
	}
	return ""
}

func (x *AnomalyFinding) GetNormalizedQueryTemplate() string {
	if x != nil {
		return x.NormalizedQueryTemplate
	}
	return ""
}

func (x *AnomalyFinding) GetIsAnomalousPredict() bool {
	if x != nil {
		return x.IsAnomalousPredict
	}
	return false
}

func (x *AnomalyFinding) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

var File_v2_common_proto_anomaly_finding_entry_proto protoreflect.FileDescriptor

const file_v2_common_proto_anomaly_finding_entry_proto_rawDesc = "" +
	"\n" +
	"+v2/common/proto/anomaly_finding_entry.proto\x12.experimental.anomaly_detection.v2.common.proto\"\xa7\x02\n" +
	"\x0eAnomalyFinding\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x17\n" +
	"\adb_user\x18\x02 \x01(\tR\x06dbUser\x12\x17\n" +
	"\adb_name\x18\x03 \x01(\tR\x06dbName\x12'\n" +
	"\x0fquery_statement\x18\x04 \x01(\tR\x0equeryStatement\x12:\n" +
	"\x19normalized_query_template\x18\x05 \x01(\tR\x17normalizedQueryTemplate\x120\n" +
	"\x14is_anomalous_predict\x18\x06 \x01(\bR\x12isAnomalousPredict\x12)\n" +
	"\x10confidence_score\x18\a \x01(\x01R\x0fconfidenceScoreBmZkgithub.com/GoogleCloudPlatform/alloydb-omni-samples/experimental/anomaly-detection/v2/common/proto;commonpbb\x06proto3"

var (
	file_v2_common_proto_anomaly_finding_entry_proto_rawDescOnce sync.Once
	file_v2_common_proto_anomaly_finding_entry_proto_rawDescData []byte
)

func file_v2_common_proto_anomaly_finding_entry_proto_rawDescGZIP() []byte {
	file_v2_common_proto_anomaly_finding_entry_proto_rawDescOnce.Do(func() {
		file_v2_common_proto_anomaly_finding_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_common_proto_anomaly_finding_entry_proto_rawDesc), len(file_v2_common_proto_anomaly_finding_entry_proto_rawDesc)))
	})
	return file_v2_common_proto_anomaly_finding_entry_proto_rawDescData
}

var file_v2_common_proto_anomaly_finding_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_common_proto_anomaly_finding_entry_proto_goTypes = []any{
	(*AnomalyFinding)(nil), // 0: experimental.anomaly_detection.v2.common.proto.AnomalyFinding
}
var file_v2_common_proto_anomaly_finding_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_common_proto_anomaly_finding_entry_proto_init() }
func file_v2_common_proto_anomaly_finding_entry_proto_init() {
	if File_v2_common_proto_anomaly_finding_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_common_proto_anomaly_finding_entry_proto_rawDesc), len(file_v2_common_proto_anomaly_finding_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_common_proto_anomaly_finding_entry_proto_goTypes,
		DependencyIndexes: file_v2_common_proto_anomaly_finding_entry_proto_depIdxs,
		MessageInfos:      file_v2_common_proto_anomaly_finding_entry_proto_msgTypes,
	}.Build()
	File_v2_common_proto_anomaly_finding_entry_proto = out.File
	file_v2_common_proto_anomaly_finding_entry_proto_goTypes = nil
	file_v2_common_proto_anomaly_finding_entry_proto_depIdxs = nil
}
