// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v2/common/proto/model.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scenario-1: Deviation from Regular Traffic Pattern
type TrafficDeviationModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Templates with probability >= anomaly threshold ratio.
	NormalTemplates []string `protobuf:"bytes,1,rep,name=normal_templates,json=normalTemplates,proto3" json:"normal_templates,omitempty"`
	// key: anomalous templates with probability < anomaly threshold ratio.
	// value: confidence score.
	AnomalyScores map[string]float64 `protobuf:"bytes,2,rep,name=anomaly_scores,json=anomalyScores,proto3" json:"anomaly_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficDeviationModel) Reset() {
	*x = TrafficDeviationModel{}
	mi := &file_v2_common_proto_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficDeviationModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficDeviationModel) ProtoMessage() {}

func (x *TrafficDeviationModel) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficDeviationModel.ProtoReflect.Descriptor instead.
func (*TrafficDeviationModel) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficDeviationModel) GetNormalTemplates() []string {
	if x != nil {
		return x.NormalTemplates
	}
	return nil
}

func (x *TrafficDeviationModel) GetAnomalyScores() map[string]float64 {
	if x != nil {
		return x.AnomalyScores
	}
	return nil
}

type TrafficDeviationTrainingConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AnomalyThresholdRatio float64                `protobuf:"fixed64,1,opt,name=anomaly_threshold_ratio,json=anomalyThresholdRatio,proto3" json:"anomaly_threshold_ratio,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrafficDeviationTrainingConfig) Reset() {
	*x = TrafficDeviationTrainingConfig{}
	mi := &file_v2_common_proto_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficDeviationTrainingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficDeviationTrainingConfig) ProtoMessage() {}

func (x *TrafficDeviationTrainingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficDeviationTrainingConfig.ProtoReflect.Descriptor instead.
func (*TrafficDeviationTrainingConfig) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficDeviationTrainingConfig) GetAnomalyThresholdRatio() float64 {
	if x != nil {
		return x.AnomalyThresholdRatio
	}
	return 0
}

type TrafficDeviationScenario struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	ModelData     *TrafficDeviationModel          `protobuf:"bytes,1,opt,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`
	Config        *TrafficDeviationTrainingConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficDeviationScenario) Reset() {
	*x = TrafficDeviationScenario{}
	mi := &file_v2_common_proto_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficDeviationScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficDeviationScenario) ProtoMessage() {}

func (x *TrafficDeviationScenario) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficDeviationScenario.ProtoReflect.Descriptor instead.
func (*TrafficDeviationScenario) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficDeviationScenario) GetModelData() *TrafficDeviationModel {
	if x != nil {
		return x.ModelData
	}
	return nil
}

func (x *TrafficDeviationScenario) GetConfig() *TrafficDeviationTrainingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CycleBucketKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbUser        string                 `protobuf:"bytes,1,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	QueryTemplate string                 `protobuf:"bytes,2,opt,name=query_template,json=queryTemplate,proto3" json:"query_template,omitempty"`
	// The relative index of the bucket within a cycle
	// (absolute_index % buckets_per_cycle).
	BucketIndex   int64 `protobuf:"varint,3,opt,name=bucket_index,json=bucketIndex,proto3" json:"bucket_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CycleBucketKey) Reset() {
	*x = CycleBucketKey{}
	mi := &file_v2_common_proto_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CycleBucketKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleBucketKey) ProtoMessage() {}

func (x *CycleBucketKey) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleBucketKey.ProtoReflect.Descriptor instead.
func (*CycleBucketKey) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{3}
}

func (x *CycleBucketKey) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *CycleBucketKey) GetQueryTemplate() string {
	if x != nil {
		return x.QueryTemplate
	}
	return ""
}

func (x *CycleBucketKey) GetBucketIndex() int64 {
	if x != nil {
		return x.BucketIndex
	}
	return 0
}

type VolumetricBaseline struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Mean   float64                `protobuf:"fixed64,1,opt,name=mean,proto3" json:"mean,omitempty"`
	StdDev float64                `protobuf:"fixed64,2,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"`
	// mean + deviation_margin
	UpperThreshold float64 `protobuf:"fixed64,3,opt,name=upper_threshold,json=upperThreshold,proto3" json:"upper_threshold,omitempty"`
	// std_dev_multiplier * std_dev
	DeviationMargin float64 `protobuf:"fixed64,4,opt,name=deviation_margin,json=deviationMargin,proto3" json:"deviation_margin,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VolumetricBaseline) Reset() {
	*x = VolumetricBaseline{}
	mi := &file_v2_common_proto_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumetricBaseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumetricBaseline) ProtoMessage() {}

func (x *VolumetricBaseline) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumetricBaseline.ProtoReflect.Descriptor instead.
func (*VolumetricBaseline) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{4}
}

func (x *VolumetricBaseline) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *VolumetricBaseline) GetStdDev() float64 {
	if x != nil {
		return x.StdDev
	}
	return 0
}

func (x *VolumetricBaseline) GetUpperThreshold() float64 {
	if x != nil {
		return x.UpperThreshold
	}
	return 0
}

func (x *VolumetricBaseline) GetDeviationMargin() float64 {
	if x != nil {
		return x.DeviationMargin
	}
	return 0
}

type VolumetricBaselineEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CycleBucketKey        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *VolumetricBaseline    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumetricBaselineEntry) Reset() {
	*x = VolumetricBaselineEntry{}
	mi := &file_v2_common_proto_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumetricBaselineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumetricBaselineEntry) ProtoMessage() {}

func (x *VolumetricBaselineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumetricBaselineEntry.ProtoReflect.Descriptor instead.
func (*VolumetricBaselineEntry) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{5}
}

func (x *VolumetricBaselineEntry) GetKey() *CycleBucketKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *VolumetricBaselineEntry) GetValue() *VolumetricBaseline {
	if x != nil {
		return x.Value
	}
	return nil
}

// Defines the temporal structure of a recurring cycle divided into buckets.
type CycleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The duration of a single bucket (e.g., 1 hour).
	BucketDuration *durationpb.Duration `protobuf:"bytes,1,opt,name=bucket_duration,json=bucketDuration,proto3" json:"bucket_duration,omitempty"`
	// The duration of one complete cycle (e.g., 7 days for a weekly cycle).
	CycleDuration *durationpb.Duration `protobuf:"bytes,2,opt,name=cycle_duration,json=cycleDuration,proto3" json:"cycle_duration,omitempty"`
	// Total number of buckets in one cycle
	// (cycle_duration / bucket_duration).
	BucketsPerCycle int64 `protobuf:"varint,3,opt,name=buckets_per_cycle,json=bucketsPerCycle,proto3" json:"buckets_per_cycle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CycleConfig) Reset() {
	*x = CycleConfig{}
	mi := &file_v2_common_proto_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CycleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleConfig) ProtoMessage() {}

func (x *CycleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleConfig.ProtoReflect.Descriptor instead.
func (*CycleConfig) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{6}
}

func (x *CycleConfig) GetBucketDuration() *durationpb.Duration {
	if x != nil {
		return x.BucketDuration
	}
	return nil
}

func (x *CycleConfig) GetCycleDuration() *durationpb.Duration {
	if x != nil {
		return x.CycleDuration
	}
	return nil
}

func (x *CycleConfig) GetBucketsPerCycle() int64 {
	if x != nil {
		return x.BucketsPerCycle
	}
	return 0
}

// Scenario-2: Severe Spikes of Read/Write Traffic
type VolumetricSpikeModel struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entries       []*VolumetricBaselineEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	CycleConfig   *CycleConfig               `protobuf:"bytes,2,opt,name=cycle_config,json=cycleConfig,proto3" json:"cycle_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumetricSpikeModel) Reset() {
	*x = VolumetricSpikeModel{}
	mi := &file_v2_common_proto_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumetricSpikeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumetricSpikeModel) ProtoMessage() {}

func (x *VolumetricSpikeModel) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumetricSpikeModel.ProtoReflect.Descriptor instead.
func (*VolumetricSpikeModel) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{7}
}

func (x *VolumetricSpikeModel) GetEntries() []*VolumetricBaselineEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *VolumetricSpikeModel) GetCycleConfig() *CycleConfig {
	if x != nil {
		return x.CycleConfig
	}
	return nil
}

type VolumetricSpikeTrainingConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StdDevMultiplier float64                `protobuf:"fixed64,1,opt,name=std_dev_multiplier,json=stdDevMultiplier,proto3" json:"std_dev_multiplier,omitempty"`
	CycleConfig      *CycleConfig           `protobuf:"bytes,2,opt,name=cycle_config,json=cycleConfig,proto3" json:"cycle_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VolumetricSpikeTrainingConfig) Reset() {
	*x = VolumetricSpikeTrainingConfig{}
	mi := &file_v2_common_proto_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumetricSpikeTrainingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumetricSpikeTrainingConfig) ProtoMessage() {}

func (x *VolumetricSpikeTrainingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumetricSpikeTrainingConfig.ProtoReflect.Descriptor instead.
func (*VolumetricSpikeTrainingConfig) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{8}
}

func (x *VolumetricSpikeTrainingConfig) GetStdDevMultiplier() float64 {
	if x != nil {
		return x.StdDevMultiplier
	}
	return 0
}

func (x *VolumetricSpikeTrainingConfig) GetCycleConfig() *CycleConfig {
	if x != nil {
		return x.CycleConfig
	}
	return nil
}

type VolumetricSpikeScenario struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ModelData     *VolumetricSpikeModel          `protobuf:"bytes,1,opt,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`
	Config        *VolumetricSpikeTrainingConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumetricSpikeScenario) Reset() {
	*x = VolumetricSpikeScenario{}
	mi := &file_v2_common_proto_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumetricSpikeScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumetricSpikeScenario) ProtoMessage() {}

func (x *VolumetricSpikeScenario) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumetricSpikeScenario.ProtoReflect.Descriptor instead.
func (*VolumetricSpikeScenario) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{9}
}

func (x *VolumetricSpikeScenario) GetModelData() *VolumetricSpikeModel {
	if x != nil {
		return x.ModelData
	}
	return nil
}

func (x *VolumetricSpikeScenario) GetConfig() *VolumetricSpikeTrainingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type TemporalSilentBucketEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             *CycleBucketKey        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TemporalSilentBucketEntry) Reset() {
	*x = TemporalSilentBucketEntry{}
	mi := &file_v2_common_proto_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalSilentBucketEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalSilentBucketEntry) ProtoMessage() {}

func (x *TemporalSilentBucketEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalSilentBucketEntry.ProtoReflect.Descriptor instead.
func (*TemporalSilentBucketEntry) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{10}
}

func (x *TemporalSilentBucketEntry) GetKey() *CycleBucketKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TemporalSilentBucketEntry) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

// Scenario-3: Requests in Unexpected Time Frames
type TemporalDeviationModel struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Entries       []*TemporalSilentBucketEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	CycleConfig   *CycleConfig                 `protobuf:"bytes,2,opt,name=cycle_config,json=cycleConfig,proto3" json:"cycle_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalDeviationModel) Reset() {
	*x = TemporalDeviationModel{}
	mi := &file_v2_common_proto_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalDeviationModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalDeviationModel) ProtoMessage() {}

func (x *TemporalDeviationModel) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalDeviationModel.ProtoReflect.Descriptor instead.
func (*TemporalDeviationModel) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{11}
}

func (x *TemporalDeviationModel) GetEntries() []*TemporalSilentBucketEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *TemporalDeviationModel) GetCycleConfig() *CycleConfig {
	if x != nil {
		return x.CycleConfig
	}
	return nil
}

type TemporalDeviationTrainingConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SilentThresholdRatio float64                `protobuf:"fixed64,1,opt,name=silent_threshold_ratio,json=silentThresholdRatio,proto3" json:"silent_threshold_ratio,omitempty"`
	CycleConfig          *CycleConfig           `protobuf:"bytes,2,opt,name=cycle_config,json=cycleConfig,proto3" json:"cycle_config,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TemporalDeviationTrainingConfig) Reset() {
	*x = TemporalDeviationTrainingConfig{}
	mi := &file_v2_common_proto_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalDeviationTrainingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalDeviationTrainingConfig) ProtoMessage() {}

func (x *TemporalDeviationTrainingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalDeviationTrainingConfig.ProtoReflect.Descriptor instead.
func (*TemporalDeviationTrainingConfig) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{12}
}

func (x *TemporalDeviationTrainingConfig) GetSilentThresholdRatio() float64 {
	if x != nil {
		return x.SilentThresholdRatio
	}
	return 0
}

func (x *TemporalDeviationTrainingConfig) GetCycleConfig() *CycleConfig {
	if x != nil {
		return x.CycleConfig
	}
	return nil
}

type TemporalDeviationScenario struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	ModelData     *TemporalDeviationModel          `protobuf:"bytes,1,opt,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`
	Config        *TemporalDeviationTrainingConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalDeviationScenario) Reset() {
	*x = TemporalDeviationScenario{}
	mi := &file_v2_common_proto_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalDeviationScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalDeviationScenario) ProtoMessage() {}

func (x *TemporalDeviationScenario) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalDeviationScenario.ProtoReflect.Descriptor instead.
func (*TemporalDeviationScenario) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{13}
}

func (x *TemporalDeviationScenario) GetModelData() *TemporalDeviationModel {
	if x != nil {
		return x.ModelData
	}
	return nil
}

func (x *TemporalDeviationScenario) GetConfig() *TemporalDeviationTrainingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ModelMetadata struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TrainingTime             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=training_time,json=trainingTime,proto3" json:"training_time,omitempty"`
	TrainerVersion           string                 `protobuf:"bytes,2,opt,name=trainer_version,json=trainerVersion,proto3" json:"trainer_version,omitempty"`
	DataStartTime            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=data_start_time,json=dataStartTime,proto3" json:"data_start_time,omitempty"`
	DataEndTime              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_end_time,json=dataEndTime,proto3" json:"data_end_time,omitempty"`
	TotalLogEntriesProcessed int64                  `protobuf:"varint,5,opt,name=total_log_entries_processed,json=totalLogEntriesProcessed,proto3" json:"total_log_entries_processed,omitempty"`
	// Optional CEL expression applied to filter log entries during model
	// training.
	FilterCelExpression string `protobuf:"bytes,6,opt,name=filter_cel_expression,json=filterCelExpression,proto3" json:"filter_cel_expression,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelMetadata) Reset() {
	*x = ModelMetadata{}
	mi := &file_v2_common_proto_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadata) ProtoMessage() {}

func (x *ModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadata.ProtoReflect.Descriptor instead.
func (*ModelMetadata) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{14}
}

func (x *ModelMetadata) GetTrainingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TrainingTime
	}
	return nil
}

func (x *ModelMetadata) GetTrainerVersion() string {
	if x != nil {
		return x.TrainerVersion
	}
	return ""
}

func (x *ModelMetadata) GetDataStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DataStartTime
	}
	return nil
}

func (x *ModelMetadata) GetDataEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DataEndTime
	}
	return nil
}

func (x *ModelMetadata) GetTotalLogEntriesProcessed() int64 {
	if x != nil {
		return x.TotalLogEntriesProcessed
	}
	return 0
}

func (x *ModelMetadata) GetFilterCelExpression() string {
	if x != nil {
		return x.FilterCelExpression
	}
	return ""
}

// Wrapper wrapping all specific anomaly detection models.
type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scenario:
	//
	//	*Model_TrafficDeviation
	//	*Model_VolumetricSpike
	//	*Model_TemporalDeviation
	Scenario      isModel_Scenario `protobuf_oneof:"scenario"`
	Metadata      *ModelMetadata   `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_v2_common_proto_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_v2_common_proto_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_v2_common_proto_model_proto_rawDescGZIP(), []int{15}
}

func (x *Model) GetScenario() isModel_Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *Model) GetTrafficDeviation() *TrafficDeviationScenario {
	if x != nil {
		if x, ok := x.Scenario.(*Model_TrafficDeviation); ok {
			return x.TrafficDeviation
		}
	}
	return nil
}

func (x *Model) GetVolumetricSpike() *VolumetricSpikeScenario {
	if x != nil {
		if x, ok := x.Scenario.(*Model_VolumetricSpike); ok {
			return x.VolumetricSpike
		}
	}
	return nil
}

func (x *Model) GetTemporalDeviation() *TemporalDeviationScenario {
	if x != nil {
		if x, ok := x.Scenario.(*Model_TemporalDeviation); ok {
			return x.TemporalDeviation
		}
	}
	return nil
}

func (x *Model) GetMetadata() *ModelMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isModel_Scenario interface {
	isModel_Scenario()
}

type Model_TrafficDeviation struct {
	TrafficDeviation *TrafficDeviationScenario `protobuf:"bytes,1,opt,name=traffic_deviation,json=trafficDeviation,proto3,oneof"`
}

type Model_VolumetricSpike struct {
	VolumetricSpike *VolumetricSpikeScenario `protobuf:"bytes,2,opt,name=volumetric_spike,json=volumetricSpike,proto3,oneof"`
}

type Model_TemporalDeviation struct {
	TemporalDeviation *TemporalDeviationScenario `protobuf:"bytes,3,opt,name=temporal_deviation,json=temporalDeviation,proto3,oneof"`
}

func (*Model_TrafficDeviation) isModel_Scenario() {}

func (*Model_VolumetricSpike) isModel_Scenario() {}

func (*Model_TemporalDeviation) isModel_Scenario() {}

var File_v2_common_proto_model_proto protoreflect.FileDescriptor

const file_v2_common_proto_model_proto_rawDesc = "" +
	"\n" +
	"\x1bv2/common/proto/model.proto\x12.experimental.anomaly_detection.v2.common.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\x15TrafficDeviationModel\x12)\n" +
	"\x10normal_templates\x18\x01 \x03(\tR\x0fnormalTemplates\x12\x7f\n" +
	"\x0eanomaly_scores\x18\x02 \x03(\v2X.experimental.anomaly_detection.v2.common.proto.TrafficDeviationModel.AnomalyScoresEntryR\ranomalyScores\x1a@\n" +
	"\x12AnomalyScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"X\n" +
	"\x1eTrafficDeviationTrainingConfig\x126\n" +
	"\x17anomaly_threshold_ratio\x18\x01 \x01(\x01R\x15anomalyThresholdRatio\"\xe8\x01\n" +
	"\x18TrafficDeviationScenario\x12d\n" +
	"\n" +
	"model_data\x18\x01 \x01(\v2E.experimental.anomaly_detection.v2.common.proto.TrafficDeviationModelR\tmodelData\x12f\n" +
	"\x06config\x18\x02 \x01(\v2N.experimental.anomaly_detection.v2.common.proto.TrafficDeviationTrainingConfigR\x06config\"s\n" +
	"\x0eCycleBucketKey\x12\x17\n" +
	"\adb_user\x18\x01 \x01(\tR\x06dbUser\x12%\n" +
	"\x0equery_template\x18\x02 \x01(\tR\rqueryTemplate\x12!\n" +
	"\fbucket_index\x18\x03 \x01(\x03R\vbucketIndex\"\x95\x01\n" +
	"\x12VolumetricBaseline\x12\x12\n" +
	"\x04mean\x18\x01 \x01(\x01R\x04mean\x12\x17\n" +
	"\astd_dev\x18\x02 \x01(\x01R\x06stdDev\x12'\n" +
	"\x0fupper_threshold\x18\x03 \x01(\x01R\x0eupperThreshold\x12)\n" +
	"\x10deviation_margin\x18\x04 \x01(\x01R\x0fdeviationMargin\"\xc5\x01\n" +
	"\x17VolumetricBaselineEntry\x12P\n" +
	"\x03key\x18\x01 \x01(\v2>.experimental.anomaly_detection.v2.common.proto.CycleBucketKeyR\x03key\x12X\n" +
	"\x05value\x18\x02 \x01(\v2B.experimental.anomaly_detection.v2.common.proto.VolumetricBaselineR\x05value\"\xbf\x01\n" +
	"\vCycleConfig\x12B\n" +
	"\x0fbucket_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0ebucketDuration\x12@\n" +
	"\x0ecycle_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rcycleDuration\x12*\n" +
	"\x11buckets_per_cycle\x18\x03 \x01(\x03R\x0fbucketsPerCycle\"\xd9\x01\n" +
	"\x14VolumetricSpikeModel\x12a\n" +
	"\aentries\x18\x01 \x03(\v2G.experimental.anomaly_detection.v2.common.proto.VolumetricBaselineEntryR\aentries\x12^\n" +
	"\fcycle_config\x18\x02 \x01(\v2;.experimental.anomaly_detection.v2.common.proto.CycleConfigR\vcycleConfig\"\xad\x01\n" +
	"\x1dVolumetricSpikeTrainingConfig\x12,\n" +
	"\x12std_dev_multiplier\x18\x01 \x01(\x01R\x10stdDevMultiplier\x12^\n" +
	"\fcycle_config\x18\x02 \x01(\v2;.experimental.anomaly_detection.v2.common.proto.CycleConfigR\vcycleConfig\"\xe5\x01\n" +
	"\x17VolumetricSpikeScenario\x12c\n" +
	"\n" +
	"model_data\x18\x01 \x01(\v2D.experimental.anomaly_detection.v2.common.proto.VolumetricSpikeModelR\tmodelData\x12e\n" +
	"\x06config\x18\x02 \x01(\v2M.experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfigR\x06config\"\x98\x01\n" +
	"\x19TemporalSilentBucketEntry\x12P\n" +
	"\x03key\x18\x01 \x01(\v2>.experimental.anomaly_detection.v2.common.proto.CycleBucketKeyR\x03key\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x01R\x0fconfidenceScore\"\xdd\x01\n" +
	"\x16TemporalDeviationModel\x12c\n" +
	"\aentries\x18\x01 \x03(\v2I.experimental.anomaly_detection.v2.common.proto.TemporalSilentBucketEntryR\aentries\x12^\n" +
	"\fcycle_config\x18\x02 \x01(\v2;.experimental.anomaly_detection.v2.common.proto.CycleConfigR\vcycleConfig\"\xb7\x01\n" +
	"\x1fTemporalDeviationTrainingConfig\x124\n" +
	"\x16silent_threshold_ratio\x18\x01 \x01(\x01R\x14silentThresholdRatio\x12^\n" +
	"\fcycle_config\x18\x02 \x01(\v2;.experimental.anomaly_detection.v2.common.proto.CycleConfigR\vcycleConfig\"\xeb\x01\n" +
	"\x19TemporalDeviationScenario\x12e\n" +
	"\n" +
	"model_data\x18\x01 \x01(\v2F.experimental.anomaly_detection.v2.common.proto.TemporalDeviationModelR\tmodelData\x12g\n" +
	"\x06config\x18\x02 \x01(\v2O.experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfigR\x06config\"\xf0\x02\n" +
	"\rModelMetadata\x12?\n" +
	"\rtraining_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ftrainingTime\x12'\n" +
	"\x0ftrainer_version\x18\x02 \x01(\tR\x0etrainerVersion\x12B\n" +
	"\x0fdata_start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rdataStartTime\x12>\n" +
	"\rdata_end_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdataEndTime\x12=\n" +
	"\x1btotal_log_entries_processed\x18\x05 \x01(\x03R\x18totalLogEntriesProcessed\x122\n" +
	"\x15filter_cel_expression\x18\x06 \x01(\tR\x13filterCelExpression\"\xeb\x03\n" +
	"\x05Model\x12w\n" +
	"\x11traffic_deviation\x18\x01 \x01(\v2H.experimental.anomaly_detection.v2.common.proto.TrafficDeviationScenarioH\x00R\x10trafficDeviation\x12t\n" +
	"\x10volumetric_spike\x18\x02 \x01(\v2G.experimental.anomaly_detection.v2.common.proto.VolumetricSpikeScenarioH\x00R\x0fvolumetricSpike\x12z\n" +
	"\x12temporal_deviation\x18\x03 \x01(\v2I.experimental.anomaly_detection.v2.common.proto.TemporalDeviationScenarioH\x00R\x11temporalDeviation\x12^\n" +
	"\bmetadata\x18\x04 \x01(\v2=.experimental.anomaly_detection.v2.common.proto.ModelMetadataH\x01R\bmetadata\x88\x01\x01B\n" +
	"\n" +
	"\bscenarioB\v\n" +
	"\t_metadataBmZkgithub.com/GoogleCloudPlatform/alloydb-omni-samples/experimental/anomaly-detection/v2/common/proto;commonpbb\x06proto3"

var (
	file_v2_common_proto_model_proto_rawDescOnce sync.Once
	file_v2_common_proto_model_proto_rawDescData []byte
)

func file_v2_common_proto_model_proto_rawDescGZIP() []byte {
	file_v2_common_proto_model_proto_rawDescOnce.Do(func() {
		file_v2_common_proto_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_common_proto_model_proto_rawDesc), len(file_v2_common_proto_model_proto_rawDesc)))
	})
	return file_v2_common_proto_model_proto_rawDescData
}

var file_v2_common_proto_model_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v2_common_proto_model_proto_goTypes = []any{
	(*TrafficDeviationModel)(nil),           // 0: experimental.anomaly_detection.v2.common.proto.TrafficDeviationModel
	(*TrafficDeviationTrainingConfig)(nil),  // 1: experimental.anomaly_detection.v2.common.proto.TrafficDeviationTrainingConfig
	(*TrafficDeviationScenario)(nil),        // 2: experimental.anomaly_detection.v2.common.proto.TrafficDeviationScenario
	(*CycleBucketKey)(nil),                  // 3: experimental.anomaly_detection.v2.common.proto.CycleBucketKey
	(*VolumetricBaseline)(nil),              // 4: experimental.anomaly_detection.v2.common.proto.VolumetricBaseline
	(*VolumetricBaselineEntry)(nil),         // 5: experimental.anomaly_detection.v2.common.proto.VolumetricBaselineEntry
	(*CycleConfig)(nil),                     // 6: experimental.anomaly_detection.v2.common.proto.CycleConfig
	(*VolumetricSpikeModel)(nil),            // 7: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeModel
	(*VolumetricSpikeTrainingConfig)(nil),   // 8: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfig
	(*VolumetricSpikeScenario)(nil),         // 9: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeScenario
	(*TemporalSilentBucketEntry)(nil),       // 10: experimental.anomaly_detection.v2.common.proto.TemporalSilentBucketEntry
	(*TemporalDeviationModel)(nil),          // 11: experimental.anomaly_detection.v2.common.proto.TemporalDeviationModel
	(*TemporalDeviationTrainingConfig)(nil), // 12: experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfig
	(*TemporalDeviationScenario)(nil),       // 13: experimental.anomaly_detection.v2.common.proto.TemporalDeviationScenario
	(*ModelMetadata)(nil),                   // 14: experimental.anomaly_detection.v2.common.proto.ModelMetadata
	(*Model)(nil),                           // 15: experimental.anomaly_detection.v2.common.proto.Model
	nil,                                     // 16: experimental.anomaly_detection.v2.common.proto.TrafficDeviationModel.AnomalyScoresEntry
	(*durationpb.Duration)(nil),             // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),           // 18: google.protobuf.Timestamp
}
var file_v2_common_proto_model_proto_depIdxs = []int32{
	16, // 0: experimental.anomaly_detection.v2.common.proto.TrafficDeviationModel.anomaly_scores:type_name -> experimental.anomaly_detection.v2.common.proto.TrafficDeviationModel.AnomalyScoresEntry
	0,  // 1: experimental.anomaly_detection.v2.common.proto.TrafficDeviationScenario.model_data:type_name -> experimental.anomaly_detection.v2.common.proto.TrafficDeviationModel
	1,  // 2: experimental.anomaly_detection.v2.common.proto.TrafficDeviationScenario.config:type_name -> experimental.anomaly_detection.v2.common.proto.TrafficDeviationTrainingConfig
	3,  // 3: experimental.anomaly_detection.v2.common.proto.VolumetricBaselineEntry.key:type_name -> experimental.anomaly_detection.v2.common.proto.CycleBucketKey
	4,  // 4: experimental.anomaly_detection.v2.common.proto.VolumetricBaselineEntry.value:type_name -> experimental.anomaly_detection.v2.common.proto.VolumetricBaseline
	17, // 5: experimental.anomaly_detection.v2.common.proto.CycleConfig.bucket_duration:type_name -> google.protobuf.Duration
	17, // 6: experimental.anomaly_detection.v2.common.proto.CycleConfig.cycle_duration:type_name -> google.protobuf.Duration
	5,  // 7: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeModel.entries:type_name -> experimental.anomaly_detection.v2.common.proto.VolumetricBaselineEntry
	6,  // 8: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeModel.cycle_config:type_name -> experimental.anomaly_detection.v2.common.proto.CycleConfig
	6,  // 9: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfig.cycle_config:type_name -> experimental.anomaly_detection.v2.common.proto.CycleConfig
	7,  // 10: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeScenario.model_data:type_name -> experimental.anomaly_detection.v2.common.proto.VolumetricSpikeModel
	8,  // 11: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeScenario.config:type_name -> experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfig
	3,  // 12: experimental.anomaly_detection.v2.common.proto.TemporalSilentBucketEntry.key:type_name -> experimental.anomaly_detection.v2.common.proto.CycleBucketKey
	10, // 13: experimental.anomaly_detection.v2.common.proto.TemporalDeviationModel.entries:type_name -> experimental.anomaly_detection.v2.common.proto.TemporalSilentBucketEntry
	6,  // 14: experimental.anomaly_detection.v2.common.proto.TemporalDeviationModel.cycle_config:type_name -> experimental.anomaly_detection.v2.common.proto.CycleConfig
	6,  // 15: experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfig.cycle_config:type_name -> experimental.anomaly_detection.v2.common.proto.CycleConfig
	11, // 16: experimental.anomaly_detection.v2.common.proto.TemporalDeviationScenario.model_data:type_name -> experimental.anomaly_detection.v2.common.proto.TemporalDeviationModel
	12, // 17: experimental.anomaly_detection.v2.common.proto.TemporalDeviationScenario.config:type_name -> experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfig
	18, // 18: experimental.anomaly_detection.v2.common.proto.ModelMetadata.training_time:type_name -> google.protobuf.Timestamp
	18, // 19: experimental.anomaly_detection.v2.common.proto.ModelMetadata.data_start_time:type_name -> google.protobuf.Timestamp
	18, // 20: experimental.anomaly_detection.v2.common.proto.ModelMetadata.data_end_time:type_name -> google.protobuf.Timestamp
	2,  // 21: experimental.anomaly_detection.v2.common.proto.Model.traffic_deviation:type_name -> experimental.anomaly_detection.v2.common.proto.TrafficDeviationScenario
	9,  // 22: experimental.anomaly_detection.v2.common.proto.Model.volumetric_spike:type_name -> experimental.anomaly_detection.v2.common.proto.VolumetricSpikeScenario
	13, // 23: experimental.anomaly_detection.v2.common.proto.Model.temporal_deviation:type_name -> experimental.anomaly_detection.v2.common.proto.TemporalDeviationScenario
	14, // 24: experimental.anomaly_detection.v2.common.proto.Model.metadata:type_name -> experimental.anomaly_detection.v2.common.proto.ModelMetadata
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_v2_common_proto_model_proto_init() }
func file_v2_common_proto_model_proto_init() {
	if File_v2_common_proto_model_proto != nil {
		return
	}
	file_v2_common_proto_model_proto_msgTypes[15].OneofWrappers = []any{
		(*Model_TrafficDeviation)(nil),
		(*Model_VolumetricSpike)(nil),
		(*Model_TemporalDeviation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_common_proto_model_proto_rawDesc), len(file_v2_common_proto_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_common_proto_model_proto_goTypes,
		DependencyIndexes: file_v2_common_proto_model_proto_depIdxs,
		MessageInfos:      file_v2_common_proto_model_proto_msgTypes,
	}.Build()
	File_v2_common_proto_model_proto = out.File
	file_v2_common_proto_model_proto_goTypes = nil
	file_v2_common_proto_model_proto_depIdxs = nil
}
