{
 "title": "DBCluster Insights",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte,dbnamespace)"
    }
   },
   {
    "name": "dbcluster",
    "label": "dbcluster",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbnamespace=\"$namespace\"},dbcluster)"
    }
   },
   {
    "name": "dbinstance_type",
    "label": "dbinstance_type",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\"},dbinstance_type)"
    }
   },
   {
    "name": "dbinstance",
    "label": "dbinstance",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\", dbinstance_type=\"$dbinstance\"},dbinstance_type)"
    }
   },
   {
    "name": "dbnode_type",
    "label": "dbnode_type",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\"},dbnode_type)"
    }
   },
   {
    "name": "dbnode",
    "label": "dbnode",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\"},dbnode)"
    }
   },
   {
    "name": "disk",
    "label": "disk",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\", dbinstance_type=\"$dbinstance_type\", dbinstance=\"$dbinstance\", dbnode_type=\"$dbnode_type\", dbnode=~\"$dbnode\"},disk)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate((alloydb_omni_node_cpu_usage_second_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}/alloydb_omni_node_cpu_mcpu{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"} * 1000)[5m:])",
     "legendFormat": "percentage-{{dbnode}}"
    }
   ]
  },
  {
   "title": "Memory used and limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alloydb_omni_memory_used_byte{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}",
     "legendFormat": "used-{{dbnode}}"
    },
    {
     "expr": "alloydb_omni_memory_limit_byte{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}",
     "legendFormat": "limit-{{dbnode}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_node_storage_write_ops_count_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}[5m])",
     "legendFormat": "Write/s-{{dbnode}}"
    },
    {
     "expr": "rate(alloydb_omni_node_storage_read_ops_count_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}[5m])",
     "legendFormat": "Read/s-{{dbnode}}"
    }
   ]
  },
  {
   "title": "Disk Byte/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_node_storage_write_bytes_count_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}[5m])",
     "legendFormat": "write B/s - {{dbnode}}"
    },
    {
     "expr": "rate(alloydb_omni_node_storage_read_bytes_count_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}[5m])",
     "legendFormat": "read B/s - {{dbnode}}"
    }
   ]
  },
  {
   "title": "Network Byte/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_node_network_sent_bytes_count_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}[5m])",
     "legendFormat": "sent B/s - {{dbnode}}"
    },
    {
     "expr": "rate(alloydb_omni_node_network_received_bytes_count_total{dbcluster=\"$dbcluster\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}[5m])",
     "legendFormat": "received B/s - {{dbnode}}"
    }
   ]
  },
  {
   "title": "$disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alloydb_omni_node_storage_limit_per_disk_byte{dbcluster=\"$dbcluster\", disk=\"$disk\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}",
     "legendFormat": "limit-{{dbnode}}"
    },
    {
     "expr": "alloydb_omni_node_storage_usage_per_disk_byte{dbcluster=\"$dbcluster\", disk=\"$disk\", dbnode=~\"$dbnode\", dbnamespace=\"$namespace\"}",
     "legendFormat": "usage-{{dbnode}}"
    }
   ]
  },
  {
   "title": "Wait time - DB Node $dbnode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "repeat": "dbnode",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_instance_postgresql_wait_time_us_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", wait_event_name!=\"ClientRead\", dbnode=~\"$dbnode\"}[5m]) or rate(alloydb_omni_instance_postgresql_wait_time_second_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\", wait_event_name!=\"ClientRead\", dbnode=~\"$dbnode\"}[5m])",
     "legendFormat": "{{wait_event_name}}-{{wait_event_type}}"
    }
   ]
  },
  {
   "title": "Replication Flush Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "alloydb_omni_instance_postgresql_replication_flush_lag_ms{dbcluster=\"$dbcluster\", dbnamespace=\"$namespace\", dbnode_type=\"Primary\"}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Replication state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "alloydb_omni_instance_postgresql_replication_state{dbcluster=\"$dbcluster\", dbnode_type=\"Primary\", dbnamespace=\"$namespace\"}",
     "legendFormat": "{{application_name}}-{{state}}"
    }
   ]
  },
  {
   "title": "Replication Replay Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "alloydb_omni_instance_postgresql_replication_replay_lag_ms{dbcluster=\"$dbcluster\", dbnode_type=\"Primary\", dbnamespace=\"$namespace\"}",
     "legendFormat": "{{application_name}}"
    }
   ]
  }
 ]
}