{
 "title": "Database-Level Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_size_byte, dbnamespace)"
    }
   },
   {
    "name": "dbcluster",
    "label": "dbcluster",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_size_byte{dbnamespace=\"$namespace\"}, dbcluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AlloyDB Omni Database PostgreSQL Backends for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_backends_for_top_databases{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL New Connections for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_new_connections_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_size_byte{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Committed Transactions for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_committed_transactions_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Rolledback Transactions for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_rolledback_transactions_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Deadlock for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_deadlock_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Statements Executed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_statements_executed_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{operation_type}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Blks Hit for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_blks_hit_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Blks Read for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_blks_read_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_tuples{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}",
     "legendFormat": "{{state}} - {{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Tuples Fetched for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_fetched_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Tuples Returned for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_returned_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Tuples Inserted for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_inserted_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Tuples Updated for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_updated_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Tuples Deleted for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_tuples_deleted_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Temp Files Written for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_temp_files_written_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Temp Bytes Written for Top Databases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_temp_bytes_written_for_top_databases_count_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{database}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Insights Aggregate Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_insights_aggregate_execution_time_us_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{user}} - {{client_addr}} - {{dbnode}}"
    }
   ]
  },
  {
   "title": "AlloyDB Omni Database PostgreSQL Insights Aggregate IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(alloydb_omni_database_postgresql_insights_aggregate_io_time_us_total{dbnamespace=\"$namespace\", dbcluster=\"$dbcluster\"}[5m])",
     "legendFormat": "{{io_type}} - {{user}} - {{dbnode}}"
    }
   ]
  }
 ]
}