{
 "title": "DBCluster Fleet Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte,dbnamespace)"
    }
   },
   {
    "name": "dbcluster",
    "label": "dbcluster",
    "query": {
     "query": "label_values(alloydb_omni_node_cpu_mcpu{dbnamespace=\"$namespace\"},dbcluster)"
    }
   },
   {
    "name": "dbnode",
    "label": "dbnode",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbcluster=~\"$dbcluster\", dbnamespace=\"$namespace\"},dbnode)"
    }
   },
   { "name": "k", "query": "1,2,3,4,5,6,7,8,9,10" }
  ]
 },
 "panels": [
  {
   "title": "Total connections per DB cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (dbcluster) (\n  alloydb_omni_database_postgresql_backends{\n    dbnamespace=\"$namespace\",\n    dbcluster=~\"$dbcluster\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization % per DB cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum by (dbcluster) (\n  alloydb_omni_memory_used_byte{\n    dbnamespace=\"$namespace\",\n    dbcluster=~\"$dbcluster\",\n    dbnode=~\"$dbnode\"\n  }\n)\n/\nsum by (dbcluster) (\n  alloydb_omni_memory_limit_byte{\n    dbnamespace=\"$namespace\",\n    dbcluster=~\"$dbcluster\",\n    dbnode=~\"$dbnode\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top-K DB clusters by total storage usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk($k,\n  sum by (dbcluster) (\n    alloydb_omni_node_storage_usage_per_disk_byte{\n      dbnamespace=\"$namespace\",\n      dbcluster=~\"$dbcluster\"\n    }\n  ) / 1e9\n)",
     "legendFormat": "{{dbcluster}}"
    }
   ]
  },
  {
   "title": "Top-K DB nodes by CPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk($k,\n  100 *\n  rate(\n    alloydb_omni_node_cpu_usage_second_total{\n      dbnamespace=\"$namespace\",\n      dbcluster=~\"$dbcluster\",\n      dbnode=~\"$dbnode\"\n    }[5m]\n  )\n  /\n  (\n    alloydb_omni_node_cpu_mcpu{\n      dbnamespace=\"$namespace\",\n      dbcluster=~\"$dbcluster\",\n      dbnode=~\"$dbnode\"\n    } / 1000\n  )\n)",
     "legendFormat": "{{dbcluster}} / {{dbnode}}"
    }
   ]
  },
  {
   "title": "Top-K DB nodes by storage usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk($k,\n  sum by (dbnode, dbcluster) (\n    alloydb_omni_node_storage_usage_per_disk_byte{\n      dbnamespace=\"$namespace\",\n      dbcluster=~\"$dbcluster\",\n      dbnode=~\"$dbnode\"\n    }\n  ) / 1e9\n)",
     "legendFormat": "{{dbcluster}} / {{dbnode}}"
    }
   ]
  }
 ]
}