{
 "title": "Metrics collection metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up,dbnamespace)"
    }
   },
   {
    "name": "dbcluster",
    "query": {
     "query": "label_values(alloydb_omni_database_postgresql_up{dbnamespace=\"$namespace\"},dbcluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics collected per cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "alloydb_omni_monitor_metric_count{namespace=\"$namespace\", dbcluster=\"$dbcluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collection duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "alloydb_omni_monitor_collect_ms{namespace=\"$namespace\", dbcluster=\"$dbcluster\"}",
     "legendFormat": "{{dbnode}}"
    }
   ]
  },
  {
   "title": "Errors per cycle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alloydb_omni_monitor_error_count{namespace=\"$namespace\", dbcluster=\"$dbcluster\"}",
     "legendFormat": "{{dbnode}}"
    }
   ]
  }
 ]
}