{
 "title": "Simple DB Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte,dbnamespace)"
    }
   },
   {
    "name": "dbcluster",
    "label": "dbcluster",
    "query": {
     "query": "label_values(alloydb_omni_node_storage_limit_per_disk_byte{dbnamespace=\"$namespace\"},dbcluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections (current vs max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_backends{\n  dbnamespace=\"$namespace\",\n  dbcluster=\"$dbcluster\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used per disk (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "alloydb_omni_node_storage_usage_per_disk_byte{\n  dbnamespace=\"$namespace\",\n  dbcluster=\"$dbcluster\"\n} / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage (vCPUs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(\n  alloydb_omni_node_cpu_usage_second_total{\n    dbnamespace=\"$namespace\",\n    dbcluster=\"$dbcluster\"\n  }[5m]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n  alloydb_omni_memory_used_byte{\n    dbnamespace=\"$namespace\",\n    dbcluster=\"$dbcluster\"\n  }\n/\n  alloydb_omni_memory_limit_byte{\n    dbnamespace=\"$namespace\",\n    dbcluster=\"$dbcluster\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alloydb_omni_database_postgresql_up{\n  dbnamespace=\"$namespace\",\n  dbcluster=\"$dbcluster\"\n}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}