// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v1/generator/proto/audit_log_entry.proto

package generatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents an audit log entry, used both for synthetic data generation
// and for log ingestion by the anomaly detection service application.
type AuditLogEntry struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NormalizedQueryTemplate string                 `protobuf:"bytes,1,opt,name=normalized_query_template,json=normalizedQueryTemplate,proto3" json:"normalized_query_template,omitempty"`
	QueryStatement          string                 `protobuf:"bytes,2,opt,name=query_statement,json=queryStatement,proto3" json:"query_statement,omitempty"`
	DbUser                  string                 `protobuf:"bytes,3,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbName                  string                 `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	// Ground truth label (true: anomalous, false: normal).
	// Optional for live logs sent to the service application.
	IsGroundTruthAnomalous bool `protobuf:"varint,5,opt,name=is_ground_truth_anomalous,json=isGroundTruthAnomalous,proto3" json:"is_ground_truth_anomalous,omitempty"`
	// Query execution timestamp.
	TimestampMs   int64 `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_v1_generator_proto_audit_log_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_audit_log_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_audit_log_entry_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLogEntry) GetNormalizedQueryTemplate() string {
	if x != nil {
		return x.NormalizedQueryTemplate
	}
	return ""
}

func (x *AuditLogEntry) GetQueryStatement() string {
	if x != nil {
		return x.QueryStatement
	}
	return ""
}

func (x *AuditLogEntry) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *AuditLogEntry) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *AuditLogEntry) GetIsGroundTruthAnomalous() bool {
	if x != nil {
		return x.IsGroundTruthAnomalous
	}
	return false
}

func (x *AuditLogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_v1_generator_proto_audit_log_entry_proto protoreflect.FileDescriptor

const file_v1_generator_proto_audit_log_entry_proto_rawDesc = "" +
	"\n" +
	"(v1/generator/proto/audit_log_entry.proto\x121experimental.anomaly_detection.v1.generator.proto\"\x84\x02\n" +
	"\rAuditLogEntry\x12:\n" +
	"\x19normalized_query_template\x18\x01 \x01(\tR\x17normalizedQueryTemplate\x12'\n" +
	"\x0fquery_statement\x18\x02 \x01(\tR\x0equeryStatement\x12\x17\n" +
	"\adb_user\x18\x03 \x01(\tR\x06dbUser\x12\x17\n" +
	"\adb_name\x18\x04 \x01(\tR\x06dbName\x129\n" +
	"\x19is_ground_truth_anomalous\x18\x05 \x01(\bR\x16isGroundTruthAnomalous\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMsBsZqgithub.com/GoogleCloudPlatform/alloydb-omni-samples/experimental/anomaly-detection/v1/generator/proto;generatorpbb\x06proto3"

var (
	file_v1_generator_proto_audit_log_entry_proto_rawDescOnce sync.Once
	file_v1_generator_proto_audit_log_entry_proto_rawDescData []byte
)

func file_v1_generator_proto_audit_log_entry_proto_rawDescGZIP() []byte {
	file_v1_generator_proto_audit_log_entry_proto_rawDescOnce.Do(func() {
		file_v1_generator_proto_audit_log_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_generator_proto_audit_log_entry_proto_rawDesc), len(file_v1_generator_proto_audit_log_entry_proto_rawDesc)))
	})
	return file_v1_generator_proto_audit_log_entry_proto_rawDescData
}

var file_v1_generator_proto_audit_log_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_generator_proto_audit_log_entry_proto_goTypes = []any{
	(*AuditLogEntry)(nil), // 0: experimental.anomaly_detection.v1.generator.proto.AuditLogEntry
}
var file_v1_generator_proto_audit_log_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_generator_proto_audit_log_entry_proto_init() }
func file_v1_generator_proto_audit_log_entry_proto_init() {
	if File_v1_generator_proto_audit_log_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_generator_proto_audit_log_entry_proto_rawDesc), len(file_v1_generator_proto_audit_log_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_generator_proto_audit_log_entry_proto_goTypes,
		DependencyIndexes: file_v1_generator_proto_audit_log_entry_proto_depIdxs,
		MessageInfos:      file_v1_generator_proto_audit_log_entry_proto_msgTypes,
	}.Build()
	File_v1_generator_proto_audit_log_entry_proto = out.File
	file_v1_generator_proto_audit_log_entry_proto_goTypes = nil
	file_v1_generator_proto_audit_log_entry_proto_depIdxs = nil
}
