// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v1/generator/proto/query_template_config.proto

package generatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query template configuration schema for synthetic data generation tool.
type QueryTemplateConfigs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scenario:
	//
	//	*QueryTemplateConfigs_WeightedSampling
	//	*QueryTemplateConfigs_BucketSampling
	Scenario      isQueryTemplateConfigs_Scenario `protobuf_oneof:"scenario"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTemplateConfigs) Reset() {
	*x = QueryTemplateConfigs{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTemplateConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTemplateConfigs) ProtoMessage() {}

func (x *QueryTemplateConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTemplateConfigs.ProtoReflect.Descriptor instead.
func (*QueryTemplateConfigs) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{0}
}

func (x *QueryTemplateConfigs) GetScenario() isQueryTemplateConfigs_Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *QueryTemplateConfigs) GetWeightedSampling() *WeightedSamplingConfig {
	if x != nil {
		if x, ok := x.Scenario.(*QueryTemplateConfigs_WeightedSampling); ok {
			return x.WeightedSampling
		}
	}
	return nil
}

func (x *QueryTemplateConfigs) GetBucketSampling() *BucketSamplingConfig {
	if x != nil {
		if x, ok := x.Scenario.(*QueryTemplateConfigs_BucketSampling); ok {
			return x.BucketSampling
		}
	}
	return nil
}

type isQueryTemplateConfigs_Scenario interface {
	isQueryTemplateConfigs_Scenario()
}

type QueryTemplateConfigs_WeightedSampling struct {
	WeightedSampling *WeightedSamplingConfig `protobuf:"bytes,1,opt,name=weighted_sampling,json=weightedSampling,proto3,oneof"`
}

type QueryTemplateConfigs_BucketSampling struct {
	BucketSampling *BucketSamplingConfig `protobuf:"bytes,2,opt,name=bucket_sampling,json=bucketSampling,proto3,oneof"`
}

func (*QueryTemplateConfigs_WeightedSampling) isQueryTemplateConfigs_Scenario() {}

func (*QueryTemplateConfigs_BucketSampling) isQueryTemplateConfigs_Scenario() {}

type WeightedSamplingConfig struct {
	state                protoimpl.MessageState         `protogen:"open.v1"`
	QueryTemplateConfigs []*WeightedQueryTemplateConfig `protobuf:"bytes,1,rep,name=query_template_configs,json=queryTemplateConfigs,proto3" json:"query_template_configs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WeightedSamplingConfig) Reset() {
	*x = WeightedSamplingConfig{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedSamplingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedSamplingConfig) ProtoMessage() {}

func (x *WeightedSamplingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedSamplingConfig.ProtoReflect.Descriptor instead.
func (*WeightedSamplingConfig) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{1}
}

func (x *WeightedSamplingConfig) GetQueryTemplateConfigs() []*WeightedQueryTemplateConfig {
	if x != nil {
		return x.QueryTemplateConfigs
	}
	return nil
}

type BucketSamplingConfig struct {
	state                protoimpl.MessageState       `protogen:"open.v1"`
	QueryTemplateConfigs []*BucketQueryTemplateConfig `protobuf:"bytes,1,rep,name=query_template_configs,json=queryTemplateConfigs,proto3" json:"query_template_configs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BucketSamplingConfig) Reset() {
	*x = BucketSamplingConfig{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSamplingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSamplingConfig) ProtoMessage() {}

func (x *BucketSamplingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSamplingConfig.ProtoReflect.Descriptor instead.
func (*BucketSamplingConfig) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{2}
}

func (x *BucketSamplingConfig) GetQueryTemplateConfigs() []*BucketQueryTemplateConfig {
	if x != nil {
		return x.QueryTemplateConfigs
	}
	return nil
}

type WeightedQueryTemplateConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Template *QueryTemplateConfig   `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	// Relative weight for random sampling, governing the distribution between
	// normal and anomalous traffic.
	ProbabilityWeight float64 `protobuf:"fixed64,2,opt,name=probability_weight,json=probabilityWeight,proto3" json:"probability_weight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WeightedQueryTemplateConfig) Reset() {
	*x = WeightedQueryTemplateConfig{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightedQueryTemplateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedQueryTemplateConfig) ProtoMessage() {}

func (x *WeightedQueryTemplateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedQueryTemplateConfig.ProtoReflect.Descriptor instead.
func (*WeightedQueryTemplateConfig) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{3}
}

func (x *WeightedQueryTemplateConfig) GetTemplate() *QueryTemplateConfig {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *WeightedQueryTemplateConfig) GetProbabilityWeight() float64 {
	if x != nil {
		return x.ProbabilityWeight
	}
	return 0
}

type BucketQueryTemplateConfig struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Template      *QueryTemplateConfig    `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	BucketConfig  *BucketSimulationConfig `protobuf:"bytes,2,opt,name=bucket_config,json=bucketConfig,proto3" json:"bucket_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketQueryTemplateConfig) Reset() {
	*x = BucketQueryTemplateConfig{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketQueryTemplateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketQueryTemplateConfig) ProtoMessage() {}

func (x *BucketQueryTemplateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketQueryTemplateConfig.ProtoReflect.Descriptor instead.
func (*BucketQueryTemplateConfig) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{4}
}

func (x *BucketQueryTemplateConfig) GetTemplate() *QueryTemplateConfig {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *BucketQueryTemplateConfig) GetBucketConfig() *BucketSimulationConfig {
	if x != nil {
		return x.BucketConfig
	}
	return nil
}

type QueryTemplateConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "SELECT * FROM my_table WHERE field1 = %v AND field2 = %v"
	NormalizedQueryTemplate string                                      `protobuf:"bytes,1,opt,name=normalized_query_template,json=normalizedQueryTemplate,proto3" json:"normalized_query_template,omitempty"`
	PlaceholderValues       []*QueryTemplateConfig_PlaceholderValueSpec `protobuf:"bytes,2,rep,name=placeholder_values,json=placeholderValues,proto3" json:"placeholder_values,omitempty"`
	// Ground truth label (true: anomalous, false: normal) used to evaluate
	// performance of unsupervised anomaly detection models.
	IsGroundTruthAnomalous bool `protobuf:"varint,4,opt,name=is_ground_truth_anomalous,json=isGroundTruthAnomalous,proto3" json:"is_ground_truth_anomalous,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QueryTemplateConfig) Reset() {
	*x = QueryTemplateConfig{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTemplateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTemplateConfig) ProtoMessage() {}

func (x *QueryTemplateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTemplateConfig.ProtoReflect.Descriptor instead.
func (*QueryTemplateConfig) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{5}
}

func (x *QueryTemplateConfig) GetNormalizedQueryTemplate() string {
	if x != nil {
		return x.NormalizedQueryTemplate
	}
	return ""
}

func (x *QueryTemplateConfig) GetPlaceholderValues() []*QueryTemplateConfig_PlaceholderValueSpec {
	if x != nil {
		return x.PlaceholderValues
	}
	return nil
}

func (x *QueryTemplateConfig) GetIsGroundTruthAnomalous() bool {
	if x != nil {
		return x.IsGroundTruthAnomalous
	}
	return false
}

type BucketSimulationConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	DbUser string                 `protobuf:"bytes,1,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	// Baseline traffic simulation.
	QueriesPerBucketMean   float64 `protobuf:"fixed64,2,opt,name=queries_per_bucket_mean,json=queriesPerBucketMean,proto3" json:"queries_per_bucket_mean,omitempty"`
	QueriesVariationStdDev float64 `protobuf:"fixed64,3,opt,name=queries_variation_std_dev,json=queriesVariationStdDev,proto3" json:"queries_variation_std_dev,omitempty"`
	// Anomalous spike
	AnomalousSpikeProbability float64 `protobuf:"fixed64,4,opt,name=anomalous_spike_probability,json=anomalousSpikeProbability,proto3" json:"anomalous_spike_probability,omitempty"`
	AnomalousSpikeMultiplier  float64 `protobuf:"fixed64,5,opt,name=anomalous_spike_multiplier,json=anomalousSpikeMultiplier,proto3" json:"anomalous_spike_multiplier,omitempty"`
	// false: Uniform distribution
	// true: Spiky/jittered distribution
	SpikyTimestampsDistribution bool `protobuf:"varint,6,opt,name=spiky_timestamps_distribution,json=spikyTimestampsDistribution,proto3" json:"spiky_timestamps_distribution,omitempty"`
	// Regular peak to simulate traffic variations in a day.
	PeakWindows []*PeakWindow `protobuf:"bytes,7,rep,name=peak_windows,json=peakWindows,proto3" json:"peak_windows,omitempty"`
	// 0.0 represents a silent weekend (e.g., offices/clinics).
	// > 1.0 represents a busy weekend (e.g., restaurants/stores).
	WeekendTrafficMultiplier *float64 `protobuf:"fixed64,8,opt,name=weekend_traffic_multiplier,json=weekendTrafficMultiplier,proto3,oneof" json:"weekend_traffic_multiplier,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BucketSimulationConfig) Reset() {
	*x = BucketSimulationConfig{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSimulationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSimulationConfig) ProtoMessage() {}

func (x *BucketSimulationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSimulationConfig.ProtoReflect.Descriptor instead.
func (*BucketSimulationConfig) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{6}
}

func (x *BucketSimulationConfig) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *BucketSimulationConfig) GetQueriesPerBucketMean() float64 {
	if x != nil {
		return x.QueriesPerBucketMean
	}
	return 0
}

func (x *BucketSimulationConfig) GetQueriesVariationStdDev() float64 {
	if x != nil {
		return x.QueriesVariationStdDev
	}
	return 0
}

func (x *BucketSimulationConfig) GetAnomalousSpikeProbability() float64 {
	if x != nil {
		return x.AnomalousSpikeProbability
	}
	return 0
}

func (x *BucketSimulationConfig) GetAnomalousSpikeMultiplier() float64 {
	if x != nil {
		return x.AnomalousSpikeMultiplier
	}
	return 0
}

func (x *BucketSimulationConfig) GetSpikyTimestampsDistribution() bool {
	if x != nil {
		return x.SpikyTimestampsDistribution
	}
	return false
}

func (x *BucketSimulationConfig) GetPeakWindows() []*PeakWindow {
	if x != nil {
		return x.PeakWindows
	}
	return nil
}

func (x *BucketSimulationConfig) GetWeekendTrafficMultiplier() float64 {
	if x != nil && x.WeekendTrafficMultiplier != nil {
		return *x.WeekendTrafficMultiplier
	}
	return 0
}

type PeakWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowName    string                 `protobuf:"bytes,1,opt,name=window_name,json=windowName,proto3" json:"window_name,omitempty"` // "day", "night" or custom values
	HourStart     int32                  `protobuf:"varint,2,opt,name=hour_start,json=hourStart,proto3" json:"hour_start,omitempty"`
	HourEnd       int32                  `protobuf:"varint,3,opt,name=hour_end,json=hourEnd,proto3" json:"hour_end,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,4,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeakWindow) Reset() {
	*x = PeakWindow{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeakWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeakWindow) ProtoMessage() {}

func (x *PeakWindow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeakWindow.ProtoReflect.Descriptor instead.
func (*PeakWindow) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{7}
}

func (x *PeakWindow) GetWindowName() string {
	if x != nil {
		return x.WindowName
	}
	return ""
}

func (x *PeakWindow) GetHourStart() int32 {
	if x != nil {
		return x.HourStart
	}
	return 0
}

func (x *PeakWindow) GetHourEnd() int32 {
	if x != nil {
		return x.HourEnd
	}
	return 0
}

func (x *PeakWindow) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

// Define value-generation constraints specific to each placeholder.
type QueryTemplateConfig_PlaceholderValueSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type-specific constraint specification.
	//
	// Types that are valid to be assigned to Placeholder:
	//
	//	*QueryTemplateConfig_PlaceholderValueSpec_IntPlaceholder
	//	*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder_
	//	*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder_
	Placeholder   isQueryTemplateConfig_PlaceholderValueSpec_Placeholder `protobuf_oneof:"placeholder"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTemplateConfig_PlaceholderValueSpec) Reset() {
	*x = QueryTemplateConfig_PlaceholderValueSpec{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTemplateConfig_PlaceholderValueSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTemplateConfig_PlaceholderValueSpec) ProtoMessage() {}

func (x *QueryTemplateConfig_PlaceholderValueSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTemplateConfig_PlaceholderValueSpec.ProtoReflect.Descriptor instead.
func (*QueryTemplateConfig_PlaceholderValueSpec) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{5, 0}
}

func (x *QueryTemplateConfig_PlaceholderValueSpec) GetPlaceholder() isQueryTemplateConfig_PlaceholderValueSpec_Placeholder {
	if x != nil {
		return x.Placeholder
	}
	return nil
}

func (x *QueryTemplateConfig_PlaceholderValueSpec) GetIntPlaceholder() *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder {
	if x != nil {
		if x, ok := x.Placeholder.(*QueryTemplateConfig_PlaceholderValueSpec_IntPlaceholder); ok {
			return x.IntPlaceholder
		}
	}
	return nil
}

func (x *QueryTemplateConfig_PlaceholderValueSpec) GetFloatPlaceholder() *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder {
	if x != nil {
		if x, ok := x.Placeholder.(*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder_); ok {
			return x.FloatPlaceholder
		}
	}
	return nil
}

func (x *QueryTemplateConfig_PlaceholderValueSpec) GetStringPlaceholder() *QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder {
	if x != nil {
		if x, ok := x.Placeholder.(*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder_); ok {
			return x.StringPlaceholder
		}
	}
	return nil
}

type isQueryTemplateConfig_PlaceholderValueSpec_Placeholder interface {
	isQueryTemplateConfig_PlaceholderValueSpec_Placeholder()
}

type QueryTemplateConfig_PlaceholderValueSpec_IntPlaceholder struct {
	IntPlaceholder *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder `protobuf:"bytes,1,opt,name=int_placeholder,json=intPlaceholder,proto3,oneof"`
}

type QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder_ struct {
	FloatPlaceholder *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder `protobuf:"bytes,2,opt,name=float_placeholder,json=floatPlaceholder,proto3,oneof"`
}

type QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder_ struct {
	StringPlaceholder *QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder `protobuf:"bytes,3,opt,name=string_placeholder,json=stringPlaceholder,proto3,oneof"`
}

func (*QueryTemplateConfig_PlaceholderValueSpec_IntPlaceholder) isQueryTemplateConfig_PlaceholderValueSpec_Placeholder() {
}

func (*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder_) isQueryTemplateConfig_PlaceholderValueSpec_Placeholder() {
}

func (*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder_) isQueryTemplateConfig_PlaceholderValueSpec_Placeholder() {
}

type QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) Reset() {
	*x = QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) ProtoMessage() {}

func (x *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder.ProtoReflect.Descriptor instead.
func (*QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) Reset() {
	*x = QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) ProtoMessage() {}

func (x *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder.ProtoReflect.Descriptor instead.
func (*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{5, 0, 1}
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowedValues []string               `protobuf:"bytes,1,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder) Reset() {
	*x = QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder{}
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder) ProtoMessage() {}

func (x *QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generator_proto_query_template_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder.ProtoReflect.Descriptor instead.
func (*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder) Descriptor() ([]byte, []int) {
	return file_v1_generator_proto_query_template_config_proto_rawDescGZIP(), []int{5, 0, 2}
}

func (x *QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder) GetAllowedValues() []string {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

var File_v1_generator_proto_query_template_config_proto protoreflect.FileDescriptor

const file_v1_generator_proto_query_template_config_proto_rawDesc = "" +
	"\n" +
	".v1/generator/proto/query_template_config.proto\x121experimental.anomaly_detection.v1.generator.proto\"\x90\x02\n" +
	"\x14QueryTemplateConfigs\x12x\n" +
	"\x11weighted_sampling\x18\x01 \x01(\v2I.experimental.anomaly_detection.v1.generator.proto.WeightedSamplingConfigH\x00R\x10weightedSampling\x12r\n" +
	"\x0fbucket_sampling\x18\x02 \x01(\v2G.experimental.anomaly_detection.v1.generator.proto.BucketSamplingConfigH\x00R\x0ebucketSamplingB\n" +
	"\n" +
	"\bscenario\"\x9f\x01\n" +
	"\x16WeightedSamplingConfig\x12\x84\x01\n" +
	"\x16query_template_configs\x18\x01 \x03(\v2N.experimental.anomaly_detection.v1.generator.proto.WeightedQueryTemplateConfigR\x14queryTemplateConfigs\"\x9b\x01\n" +
	"\x14BucketSamplingConfig\x12\x82\x01\n" +
	"\x16query_template_configs\x18\x01 \x03(\v2L.experimental.anomaly_detection.v1.generator.proto.BucketQueryTemplateConfigR\x14queryTemplateConfigs\"\xb0\x01\n" +
	"\x1bWeightedQueryTemplateConfig\x12b\n" +
	"\btemplate\x18\x01 \x01(\v2F.experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfigR\btemplate\x12-\n" +
	"\x12probability_weight\x18\x02 \x01(\x01R\x11probabilityWeight\"\xef\x01\n" +
	"\x19BucketQueryTemplateConfig\x12b\n" +
	"\btemplate\x18\x01 \x01(\v2F.experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfigR\btemplate\x12n\n" +
	"\rbucket_config\x18\x02 \x01(\v2I.experimental.anomaly_detection.v1.generator.proto.BucketSimulationConfigR\fbucketConfig\"\xca\a\n" +
	"\x13QueryTemplateConfig\x12:\n" +
	"\x19normalized_query_template\x18\x01 \x01(\tR\x17normalizedQueryTemplate\x12\x8a\x01\n" +
	"\x12placeholder_values\x18\x02 \x03(\v2[.experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpecR\x11placeholderValues\x129\n" +
	"\x19is_ground_truth_anomalous\x18\x04 \x01(\bR\x16isGroundTruthAnomalous\x1a\xae\x05\n" +
	"\x14PlaceholderValueSpec\x12\x99\x01\n" +
	"\x0fint_placeholder\x18\x01 \x01(\v2n.experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.IntegerPlaceholderH\x00R\x0eintPlaceholder\x12\x9b\x01\n" +
	"\x11float_placeholder\x18\x02 \x01(\v2l.experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.FloatPlaceholderH\x00R\x10floatPlaceholder\x12\x9e\x01\n" +
	"\x12string_placeholder\x18\x03 \x01(\v2m.experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.StringPlaceholderH\x00R\x11stringPlaceholder\x1a8\n" +
	"\x12IntegerPlaceholder\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x1a6\n" +
	"\x10FloatPlaceholder\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x1a:\n" +
	"\x11StringPlaceholder\x12%\n" +
	"\x0eallowed_values\x18\x01 \x03(\tR\rallowedValuesB\r\n" +
	"\vplaceholder\"\xa9\x04\n" +
	"\x16BucketSimulationConfig\x12\x17\n" +
	"\adb_user\x18\x01 \x01(\tR\x06dbUser\x125\n" +
	"\x17queries_per_bucket_mean\x18\x02 \x01(\x01R\x14queriesPerBucketMean\x129\n" +
	"\x19queries_variation_std_dev\x18\x03 \x01(\x01R\x16queriesVariationStdDev\x12>\n" +
	"\x1banomalous_spike_probability\x18\x04 \x01(\x01R\x19anomalousSpikeProbability\x12<\n" +
	"\x1aanomalous_spike_multiplier\x18\x05 \x01(\x01R\x18anomalousSpikeMultiplier\x12B\n" +
	"\x1dspiky_timestamps_distribution\x18\x06 \x01(\bR\x1bspikyTimestampsDistribution\x12`\n" +
	"\fpeak_windows\x18\a \x03(\v2=.experimental.anomaly_detection.v1.generator.proto.PeakWindowR\vpeakWindows\x12A\n" +
	"\x1aweekend_traffic_multiplier\x18\b \x01(\x01H\x00R\x18weekendTrafficMultiplier\x88\x01\x01B\x1d\n" +
	"\x1b_weekend_traffic_multiplier\"\x87\x01\n" +
	"\n" +
	"PeakWindow\x12\x1f\n" +
	"\vwindow_name\x18\x01 \x01(\tR\n" +
	"windowName\x12\x1d\n" +
	"\n" +
	"hour_start\x18\x02 \x01(\x05R\thourStart\x12\x19\n" +
	"\bhour_end\x18\x03 \x01(\x05R\ahourEnd\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x01R\n" +
	"multiplierBsZqgithub.com/GoogleCloudPlatform/alloydb-omni-samples/experimental/anomaly-detection/v1/generator/proto;generatorpbb\x06proto3"

var (
	file_v1_generator_proto_query_template_config_proto_rawDescOnce sync.Once
	file_v1_generator_proto_query_template_config_proto_rawDescData []byte
)

func file_v1_generator_proto_query_template_config_proto_rawDescGZIP() []byte {
	file_v1_generator_proto_query_template_config_proto_rawDescOnce.Do(func() {
		file_v1_generator_proto_query_template_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_generator_proto_query_template_config_proto_rawDesc), len(file_v1_generator_proto_query_template_config_proto_rawDesc)))
	})
	return file_v1_generator_proto_query_template_config_proto_rawDescData
}

var file_v1_generator_proto_query_template_config_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_generator_proto_query_template_config_proto_goTypes = []any{
	(*QueryTemplateConfigs)(nil),                                        // 0: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfigs
	(*WeightedSamplingConfig)(nil),                                      // 1: experimental.anomaly_detection.v1.generator.proto.WeightedSamplingConfig
	(*BucketSamplingConfig)(nil),                                        // 2: experimental.anomaly_detection.v1.generator.proto.BucketSamplingConfig
	(*WeightedQueryTemplateConfig)(nil),                                 // 3: experimental.anomaly_detection.v1.generator.proto.WeightedQueryTemplateConfig
	(*BucketQueryTemplateConfig)(nil),                                   // 4: experimental.anomaly_detection.v1.generator.proto.BucketQueryTemplateConfig
	(*QueryTemplateConfig)(nil),                                         // 5: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig
	(*BucketSimulationConfig)(nil),                                      // 6: experimental.anomaly_detection.v1.generator.proto.BucketSimulationConfig
	(*PeakWindow)(nil),                                                  // 7: experimental.anomaly_detection.v1.generator.proto.PeakWindow
	(*QueryTemplateConfig_PlaceholderValueSpec)(nil),                    // 8: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec
	(*QueryTemplateConfig_PlaceholderValueSpec_IntegerPlaceholder)(nil), // 9: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.IntegerPlaceholder
	(*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder)(nil),   // 10: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.FloatPlaceholder
	(*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder)(nil),  // 11: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.StringPlaceholder
}
var file_v1_generator_proto_query_template_config_proto_depIdxs = []int32{
	1,  // 0: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfigs.weighted_sampling:type_name -> experimental.anomaly_detection.v1.generator.proto.WeightedSamplingConfig
	2,  // 1: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfigs.bucket_sampling:type_name -> experimental.anomaly_detection.v1.generator.proto.BucketSamplingConfig
	3,  // 2: experimental.anomaly_detection.v1.generator.proto.WeightedSamplingConfig.query_template_configs:type_name -> experimental.anomaly_detection.v1.generator.proto.WeightedQueryTemplateConfig
	4,  // 3: experimental.anomaly_detection.v1.generator.proto.BucketSamplingConfig.query_template_configs:type_name -> experimental.anomaly_detection.v1.generator.proto.BucketQueryTemplateConfig
	5,  // 4: experimental.anomaly_detection.v1.generator.proto.WeightedQueryTemplateConfig.template:type_name -> experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig
	5,  // 5: experimental.anomaly_detection.v1.generator.proto.BucketQueryTemplateConfig.template:type_name -> experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig
	6,  // 6: experimental.anomaly_detection.v1.generator.proto.BucketQueryTemplateConfig.bucket_config:type_name -> experimental.anomaly_detection.v1.generator.proto.BucketSimulationConfig
	8,  // 7: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.placeholder_values:type_name -> experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec
	7,  // 8: experimental.anomaly_detection.v1.generator.proto.BucketSimulationConfig.peak_windows:type_name -> experimental.anomaly_detection.v1.generator.proto.PeakWindow
	9,  // 9: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.int_placeholder:type_name -> experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.IntegerPlaceholder
	10, // 10: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.float_placeholder:type_name -> experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.FloatPlaceholder
	11, // 11: experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.string_placeholder:type_name -> experimental.anomaly_detection.v1.generator.proto.QueryTemplateConfig.PlaceholderValueSpec.StringPlaceholder
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_generator_proto_query_template_config_proto_init() }
func file_v1_generator_proto_query_template_config_proto_init() {
	if File_v1_generator_proto_query_template_config_proto != nil {
		return
	}
	file_v1_generator_proto_query_template_config_proto_msgTypes[0].OneofWrappers = []any{
		(*QueryTemplateConfigs_WeightedSampling)(nil),
		(*QueryTemplateConfigs_BucketSampling)(nil),
	}
	file_v1_generator_proto_query_template_config_proto_msgTypes[6].OneofWrappers = []any{}
	file_v1_generator_proto_query_template_config_proto_msgTypes[8].OneofWrappers = []any{
		(*QueryTemplateConfig_PlaceholderValueSpec_IntPlaceholder)(nil),
		(*QueryTemplateConfig_PlaceholderValueSpec_FloatPlaceholder_)(nil),
		(*QueryTemplateConfig_PlaceholderValueSpec_StringPlaceholder_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_generator_proto_query_template_config_proto_rawDesc), len(file_v1_generator_proto_query_template_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_generator_proto_query_template_config_proto_goTypes,
		DependencyIndexes: file_v1_generator_proto_query_template_config_proto_depIdxs,
		MessageInfos:      file_v1_generator_proto_query_template_config_proto_msgTypes,
	}.Build()
	File_v1_generator_proto_query_template_config_proto = out.File
	file_v1_generator_proto_query_template_config_proto_goTypes = nil
	file_v1_generator_proto_query_template_config_proto_depIdxs = nil
}
