// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v2/training_service/proto/training_service.proto

package trainingpb

import (
	proto "github.com/GoogleCloudPlatform/alloydb-omni-samples/experimental/anomaly-detection/v2/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for a model trainer.
type ModelTrainingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*ModelTrainingConfig_TrafficDeviationConfig
	//	*ModelTrainingConfig_VolumetricSpikeConfig
	//	*ModelTrainingConfig_TemporalDeviationConfig
	Config        isModelTrainingConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelTrainingConfig) Reset() {
	*x = ModelTrainingConfig{}
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelTrainingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelTrainingConfig) ProtoMessage() {}

func (x *ModelTrainingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelTrainingConfig.ProtoReflect.Descriptor instead.
func (*ModelTrainingConfig) Descriptor() ([]byte, []int) {
	return file_v2_training_service_proto_training_service_proto_rawDescGZIP(), []int{0}
}

func (x *ModelTrainingConfig) GetConfig() isModelTrainingConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ModelTrainingConfig) GetTrafficDeviationConfig() *proto.TrafficDeviationTrainingConfig {
	if x != nil {
		if x, ok := x.Config.(*ModelTrainingConfig_TrafficDeviationConfig); ok {
			return x.TrafficDeviationConfig
		}
	}
	return nil
}

func (x *ModelTrainingConfig) GetVolumetricSpikeConfig() *proto.VolumetricSpikeTrainingConfig {
	if x != nil {
		if x, ok := x.Config.(*ModelTrainingConfig_VolumetricSpikeConfig); ok {
			return x.VolumetricSpikeConfig
		}
	}
	return nil
}

func (x *ModelTrainingConfig) GetTemporalDeviationConfig() *proto.TemporalDeviationTrainingConfig {
	if x != nil {
		if x, ok := x.Config.(*ModelTrainingConfig_TemporalDeviationConfig); ok {
			return x.TemporalDeviationConfig
		}
	}
	return nil
}

type isModelTrainingConfig_Config interface {
	isModelTrainingConfig_Config()
}

type ModelTrainingConfig_TrafficDeviationConfig struct {
	TrafficDeviationConfig *proto.TrafficDeviationTrainingConfig `protobuf:"bytes,1,opt,name=traffic_deviation_config,json=trafficDeviationConfig,proto3,oneof"`
}

type ModelTrainingConfig_VolumetricSpikeConfig struct {
	VolumetricSpikeConfig *proto.VolumetricSpikeTrainingConfig `protobuf:"bytes,2,opt,name=volumetric_spike_config,json=volumetricSpikeConfig,proto3,oneof"`
}

type ModelTrainingConfig_TemporalDeviationConfig struct {
	TemporalDeviationConfig *proto.TemporalDeviationTrainingConfig `protobuf:"bytes,3,opt,name=temporal_deviation_config,json=temporalDeviationConfig,proto3,oneof"`
}

func (*ModelTrainingConfig_TrafficDeviationConfig) isModelTrainingConfig_Config() {}

func (*ModelTrainingConfig_VolumetricSpikeConfig) isModelTrainingConfig_Config() {}

func (*ModelTrainingConfig_TemporalDeviationConfig) isModelTrainingConfig_Config() {}

type TrainModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the shared training log file.
	TrainLogPath string `protobuf:"bytes,1,opt,name=train_log_path,json=trainLogPath,proto3" json:"train_log_path,omitempty"`
	// Support training multiple models in a single pass.
	TrainingConfigs []*ModelTrainingConfig `protobuf:"bytes,2,rep,name=training_configs,json=trainingConfigs,proto3" json:"training_configs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainModelsRequest) Reset() {
	*x = TrainModelsRequest{}
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainModelsRequest) ProtoMessage() {}

func (x *TrainModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainModelsRequest.ProtoReflect.Descriptor instead.
func (*TrainModelsRequest) Descriptor() ([]byte, []int) {
	return file_v2_training_service_proto_training_service_proto_rawDescGZIP(), []int{1}
}

func (x *TrainModelsRequest) GetTrainLogPath() string {
	if x != nil {
		return x.TrainLogPath
	}
	return ""
}

func (x *TrainModelsRequest) GetTrainingConfigs() []*ModelTrainingConfig {
	if x != nil {
		return x.TrainingConfigs
	}
	return nil
}

// Result for a single trained model.
type TrainedModelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelLocation string                 `protobuf:"bytes,1,opt,name=model_location,json=modelLocation,proto3" json:"model_location,omitempty"`
	Metadata      *proto.ModelMetadata   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainedModelResult) Reset() {
	*x = TrainedModelResult{}
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainedModelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainedModelResult) ProtoMessage() {}

func (x *TrainedModelResult) ProtoReflect() protoreflect.Message {
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainedModelResult.ProtoReflect.Descriptor instead.
func (*TrainedModelResult) Descriptor() ([]byte, []int) {
	return file_v2_training_service_proto_training_service_proto_rawDescGZIP(), []int{2}
}

func (x *TrainedModelResult) GetModelLocation() string {
	if x != nil {
		return x.ModelLocation
	}
	return ""
}

func (x *TrainedModelResult) GetMetadata() *proto.ModelMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TrainModelsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Results         []*TrainedModelResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TrainingSummary string                 `protobuf:"bytes,2,opt,name=training_summary,json=trainingSummary,proto3" json:"training_summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainModelsResponse) Reset() {
	*x = TrainModelsResponse{}
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainModelsResponse) ProtoMessage() {}

func (x *TrainModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_training_service_proto_training_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainModelsResponse.ProtoReflect.Descriptor instead.
func (*TrainModelsResponse) Descriptor() ([]byte, []int) {
	return file_v2_training_service_proto_training_service_proto_rawDescGZIP(), []int{3}
}

func (x *TrainModelsResponse) GetResults() []*TrainedModelResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *TrainModelsResponse) GetTrainingSummary() string {
	if x != nil {
		return x.TrainingSummary
	}
	return ""
}

var File_v2_training_service_proto_training_service_proto protoreflect.FileDescriptor

const file_v2_training_service_proto_training_service_proto_rawDesc = "" +
	"\n" +
	"0v2/training_service/proto/training_service.proto\x120experimental.anomaly_detection.v2.training.proto\x1a\x1bv2/common/proto/model.proto\"\xc6\x03\n" +
	"\x13ModelTrainingConfig\x12\x8a\x01\n" +
	"\x18traffic_deviation_config\x18\x01 \x01(\v2N.experimental.anomaly_detection.v2.common.proto.TrafficDeviationTrainingConfigH\x00R\x16trafficDeviationConfig\x12\x87\x01\n" +
	"\x17volumetric_spike_config\x18\x02 \x01(\v2M.experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfigH\x00R\x15volumetricSpikeConfig\x12\x8d\x01\n" +
	"\x19temporal_deviation_config\x18\x03 \x01(\v2O.experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfigH\x00R\x17temporalDeviationConfigB\b\n" +
	"\x06config\"\xac\x01\n" +
	"\x12TrainModelsRequest\x12$\n" +
	"\x0etrain_log_path\x18\x01 \x01(\tR\ftrainLogPath\x12p\n" +
	"\x10training_configs\x18\x02 \x03(\v2E.experimental.anomaly_detection.v2.training.proto.ModelTrainingConfigR\x0ftrainingConfigs\"\x96\x01\n" +
	"\x12TrainedModelResult\x12%\n" +
	"\x0emodel_location\x18\x01 \x01(\tR\rmodelLocation\x12Y\n" +
	"\bmetadata\x18\x02 \x01(\v2=.experimental.anomaly_detection.v2.common.proto.ModelMetadataR\bmetadata\"\xa0\x01\n" +
	"\x13TrainModelsResponse\x12^\n" +
	"\aresults\x18\x01 \x03(\v2D.experimental.anomaly_detection.v2.training.proto.TrainedModelResultR\aresults\x12)\n" +
	"\x10training_summary\x18\x02 \x01(\tR\x0ftrainingSummary2\xae\x01\n" +
	"\x0fTrainingService\x12\x9a\x01\n" +
	"\vTrainModels\x12D.experimental.anomaly_detection.v2.training.proto.TrainModelsRequest\x1aE.experimental.anomaly_detection.v2.training.proto.TrainModelsResponseByZwgithub.com/GoogleCloudPlatform/alloydb-omni-samples/experimental/anomaly-detection/v2/training_service/proto;trainingpbb\x06proto3"

var (
	file_v2_training_service_proto_training_service_proto_rawDescOnce sync.Once
	file_v2_training_service_proto_training_service_proto_rawDescData []byte
)

func file_v2_training_service_proto_training_service_proto_rawDescGZIP() []byte {
	file_v2_training_service_proto_training_service_proto_rawDescOnce.Do(func() {
		file_v2_training_service_proto_training_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_training_service_proto_training_service_proto_rawDesc), len(file_v2_training_service_proto_training_service_proto_rawDesc)))
	})
	return file_v2_training_service_proto_training_service_proto_rawDescData
}

var file_v2_training_service_proto_training_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v2_training_service_proto_training_service_proto_goTypes = []any{
	(*ModelTrainingConfig)(nil),                   // 0: experimental.anomaly_detection.v2.training.proto.ModelTrainingConfig
	(*TrainModelsRequest)(nil),                    // 1: experimental.anomaly_detection.v2.training.proto.TrainModelsRequest
	(*TrainedModelResult)(nil),                    // 2: experimental.anomaly_detection.v2.training.proto.TrainedModelResult
	(*TrainModelsResponse)(nil),                   // 3: experimental.anomaly_detection.v2.training.proto.TrainModelsResponse
	(*proto.TrafficDeviationTrainingConfig)(nil),  // 4: experimental.anomaly_detection.v2.common.proto.TrafficDeviationTrainingConfig
	(*proto.VolumetricSpikeTrainingConfig)(nil),   // 5: experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfig
	(*proto.TemporalDeviationTrainingConfig)(nil), // 6: experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfig
	(*proto.ModelMetadata)(nil),                   // 7: experimental.anomaly_detection.v2.common.proto.ModelMetadata
}
var file_v2_training_service_proto_training_service_proto_depIdxs = []int32{
	4, // 0: experimental.anomaly_detection.v2.training.proto.ModelTrainingConfig.traffic_deviation_config:type_name -> experimental.anomaly_detection.v2.common.proto.TrafficDeviationTrainingConfig
	5, // 1: experimental.anomaly_detection.v2.training.proto.ModelTrainingConfig.volumetric_spike_config:type_name -> experimental.anomaly_detection.v2.common.proto.VolumetricSpikeTrainingConfig
	6, // 2: experimental.anomaly_detection.v2.training.proto.ModelTrainingConfig.temporal_deviation_config:type_name -> experimental.anomaly_detection.v2.common.proto.TemporalDeviationTrainingConfig
	0, // 3: experimental.anomaly_detection.v2.training.proto.TrainModelsRequest.training_configs:type_name -> experimental.anomaly_detection.v2.training.proto.ModelTrainingConfig
	7, // 4: experimental.anomaly_detection.v2.training.proto.TrainedModelResult.metadata:type_name -> experimental.anomaly_detection.v2.common.proto.ModelMetadata
	2, // 5: experimental.anomaly_detection.v2.training.proto.TrainModelsResponse.results:type_name -> experimental.anomaly_detection.v2.training.proto.TrainedModelResult
	1, // 6: experimental.anomaly_detection.v2.training.proto.TrainingService.TrainModels:input_type -> experimental.anomaly_detection.v2.training.proto.TrainModelsRequest
	3, // 7: experimental.anomaly_detection.v2.training.proto.TrainingService.TrainModels:output_type -> experimental.anomaly_detection.v2.training.proto.TrainModelsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v2_training_service_proto_training_service_proto_init() }
func file_v2_training_service_proto_training_service_proto_init() {
	if File_v2_training_service_proto_training_service_proto != nil {
		return
	}
	file_v2_training_service_proto_training_service_proto_msgTypes[0].OneofWrappers = []any{
		(*ModelTrainingConfig_TrafficDeviationConfig)(nil),
		(*ModelTrainingConfig_VolumetricSpikeConfig)(nil),
		(*ModelTrainingConfig_TemporalDeviationConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_training_service_proto_training_service_proto_rawDesc), len(file_v2_training_service_proto_training_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_training_service_proto_training_service_proto_goTypes,
		DependencyIndexes: file_v2_training_service_proto_training_service_proto_depIdxs,
		MessageInfos:      file_v2_training_service_proto_training_service_proto_msgTypes,
	}.Build()
	File_v2_training_service_proto_training_service_proto = out.File
	file_v2_training_service_proto_training_service_proto_goTypes = nil
	file_v2_training_service_proto_training_service_proto_depIdxs = nil
}
