// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: v2/training_service/proto/training_service.proto

package trainingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrainingService_TrainModels_FullMethodName = "/experimental.anomaly_detection.v2.training.proto.TrainingService/TrainModels"
)

// TrainingServiceClient is the client API for TrainingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for training anomaly detection models.
type TrainingServiceClient interface {
	// Trains one or more anomaly models based on the logs and provided configs.
	// Saves the models to the specified location and pushes them to the
	// prediction service.
	TrainModels(ctx context.Context, in *TrainModelsRequest, opts ...grpc.CallOption) (*TrainModelsResponse, error)
}

type trainingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingServiceClient(cc grpc.ClientConnInterface) TrainingServiceClient {
	return &trainingServiceClient{cc}
}

func (c *trainingServiceClient) TrainModels(ctx context.Context, in *TrainModelsRequest, opts ...grpc.CallOption) (*TrainModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainModelsResponse)
	err := c.cc.Invoke(ctx, TrainingService_TrainModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainingServiceServer is the server API for TrainingService service.
// All implementations must embed UnimplementedTrainingServiceServer
// for forward compatibility.
//
// Service for training anomaly detection models.
type TrainingServiceServer interface {
	// Trains one or more anomaly models based on the logs and provided configs.
	// Saves the models to the specified location and pushes them to the
	// prediction service.
	TrainModels(context.Context, *TrainModelsRequest) (*TrainModelsResponse, error)
	mustEmbedUnimplementedTrainingServiceServer()
}

// UnimplementedTrainingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainingServiceServer struct{}

func (UnimplementedTrainingServiceServer) TrainModels(context.Context, *TrainModelsRequest) (*TrainModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrainModels not implemented")
}
func (UnimplementedTrainingServiceServer) mustEmbedUnimplementedTrainingServiceServer() {}
func (UnimplementedTrainingServiceServer) testEmbeddedByValue()                         {}

// UnsafeTrainingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingServiceServer will
// result in compilation errors.
type UnsafeTrainingServiceServer interface {
	mustEmbedUnimplementedTrainingServiceServer()
}

func RegisterTrainingServiceServer(s grpc.ServiceRegistrar, srv TrainingServiceServer) {
	// If the following call panics, it indicates UnimplementedTrainingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainingService_ServiceDesc, srv)
}

func _TrainingService_TrainModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingServiceServer).TrainModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingService_TrainModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingServiceServer).TrainModels(ctx, req.(*TrainModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainingService_ServiceDesc is the grpc.ServiceDesc for TrainingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "experimental.anomaly_detection.v2.training.proto.TrainingService",
	HandlerType: (*TrainingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrainModels",
			Handler:    _TrainingService_TrainModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/training_service/proto/training_service.proto",
}
